---
- hosts: all
  connection: local
  become: yes
  gather_facts: no
  
  vars_files:
    - /var/lib/jenkins/workspace/ansible-playbook/install/vars/main.yml
  roles:
    - { role: install }
