- name: download tomcat server packages
  get_url:
    url: "{{ tomcat_url }}"
    dest: /opt
    
- name: extract tomcat packages
  unarchive:
    src: /opt/{{ tomcat_version }}.tar.gz
    dest: /opt
    remote_src: yes

- name: start tomcat services
  shell: nohup /opt/{{ tomcat_version }}/bin/startup.sh
